#!/usr/bin/env python3

import requests

INSTANCE_URL = "http://example.com"

try:
    response = requests.get(INSTANCE_URL)
    response.raise_for_status()
    print("Instance is healthy")
    exit(0)
except requests.RequestException as e:
    print(f"Instance is unhealthy ({e})")
    exit(1)
